### ISSUE TITLE
 QCoreApplication::applicationDirPath: Please instantiate the QApplication object first

### ISSUE THREAD

**Issue by peterge1998** [flathub/com.teamspeak.TeamSpeak#30] opened 2021-11-12 19:51 UTC
#29 The problem from my issue happened again... After rebooting 3 times its gone...

**Comment by peterge1998** [comment] 2021-11-12 19:54
https://community.teamspeak.com/t/flatpak-qcoreapplication-please-instantiate-the-qapplication-object-first/28531

**Comment by Zlopez** [comment] 2021-11-13 14:04
Let's see if the upstream will respond to this.

I can see the issue on my side, but the TeamSpeak still starts.

**Comment by peterge1998** [comment] 2022-01-05 17:48
➜  ~ flatpak run com.teamspeak.TeamSpeak
QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
Qt: Session management error: None of the authentication protocols specified are supported

After the problem did not show up for many days, its showing again today. No response yet...

**Comment by Zlopez** [comment] 2022-01-06 20:07
I tried it on Fedora 35 Kinoite and the TeamSpeak is working fine. I don't even see any autentication error.

**Comment by peterge1998** [comment] 2022-01-06 21:32
> I tried it on Fedora 35 Kinoite and the TeamSpeak is working fine. I don't even see any autentication error.

I did not see it for 3 moth. Seems to occur very rarely... But when it happen it does prevent ts from starting

**Comment by Zlopez** [comment] 2022-03-14 09:17
Let's close it for now, and if it comes again, we can reopen it.

**Closed by Zlopez** 2022-03-14 09:17 UTC

**Comment by peterge1998** [comment] 2022-04-01 16:09
It did occur on my laptop once again... I wonder that i seem to be the only person who is affected by this, but it did happen now on two different machines with different versions

**Comment by torvitas** [comment] 2022-04-02 01:48
> It did occur on my laptop once again... I wonder that i seem to be the only person who is affected by this, but it did happen now on two different machines with different versions

I have had the same error every now and then.

**Comment by Zlopez** [comment] 2022-04-04 08:00
@torvitas Does it prevent you to start the TeamSpeak?

**Comment by torvitas** [comment] 2022-04-04 08:11
It does when it occurs.

**Comment by Zlopez** [comment] 2022-04-04 08:20
I see this error every time, but the application runs fine. It's hard to reproduce the error on my side and because the TeamSpeak isn't open source, I can't really debug what is happening :-/

**Comment by torvitas** [comment] 2022-04-04 08:36
I have to admit, I usually do not start teamspeak from cli. So maybe the answer should have been: When TeamSpeak does not start I as well see that error.

I just checked - I as well always get this error, even if TeamSpeak starts correctly.

**Comment by peterge1998** [comment] 2022-04-04 11:50
> I have to admit, I usually do not start teamspeak from cli. So maybe the answer should have been: When TeamSpeak does not start I as well see that error.
> 
> I just checked - I as well always get this error, even if TeamSpeak starts correctly.

I usually start it via an extension which autostarts different applications on login. However, once in a while teamspeak has not started after loggin in. If this occurs, i run `flatpak run com.temspeak.something` manually, to see why it is not starring. Thats why i opened this issue, where it is quite exactly documented when i wasnt able to launch ts. Everytime it does not start and i run it from cli, just this qapplication error is shown, nothing else...
